# Generated by Django 4.2.4 on 2023-08-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateField(verbose_name='date published')),
                ('end', models.DateField(verbose_name='date published')),
                ('number', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
